# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  resourcegroup: tailspintoys-test
  containerregistry: mcwworkshopregistryname.azurecr.io
  registryusername: mcwWorkshopRegistryName
  imagename: mcwworkshopregistryname.azurecr.io/tailspintoys/web

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        
      - name: Login to ACR
        uses: docker/login-action@v1
        with:
          registry: ${{ env.containerregistry }}
          username: ${{ env.registryusername }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ env.imagename }}:${{ github.sha }}

      - name: Upload arm templates to workflow
        uses: actions/upload-artifact@v2
        with:
          name: armtemplate
          path: ${{ github.workspace }}/armtemplate/
          
  deploy-dev:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Download armtemplate
        uses: actions/download-artifact@v2
        with:
          name: armtemplate
        
      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy resource group 
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az group create -l northeurope -n ${{ env.resourcegroup }}

      - name: Deploy ARM template
        run: |
          $output = az deployment group create --resource-group ${{ env.resourcegroup }} --template-file azuredeploy.json --parameters environment=dev --parameters administratorLogin=JallaJalla --parameters administratorLoginPassword=${{ secrets.DBPASSWORD }}
          $armOutputObj = $output | ConvertFrom-Json
          $webAppName = $armOutputObj.properties.outputs.webappname.value
          echo "webAppName=$webAppName" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
        shell: pwsh

      - name: Deploy webapp to staging slot
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az webapp config container set \
                        --resource-group ${{ env.resourcegroup }} \
                        --name ${{ env.webAppName }} \
                        --docker-custom-image-name ${{ env.imagename }}:${{ github.sha }} \
                        --docker-registry-server-password ${{ secrets.REGISTRY_PASSWORD }} \
                        --docker-registry-server-url https://${{ env.containerregistry }} \
                        --docker-registry-server-user ${{ env.registryusername }} \
                        --slot staging

      - name: Swap slots for webapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az webapp deployment slot swap -g ${{ env.resourcegroup }} -n ${{ env.webAppName }} --slot staging --target-slot production

  deploy-test:
    runs-on: ubuntu-latest
    needs: deploy-dev
    steps:
      - name: Download armtemplate
        uses: actions/download-artifact@v2
        with:
          name: armtemplate

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
    
      - name: Deploy resource group
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az group create -l northeurope -n ${{ env.resourcegroup }}

      - run: |
          $output = az deployment group create --resource-group ${{ env.resourcegroup }} --template-file azuredeploy.json --parameters environment=test --parameters administratorLogin=JallaJalla --parameters administratorLoginPassword=${{ secrets.DBPASSWORD }}
          $armOutputObj = $output | ConvertFrom-Json
          $webAppName = $armOutputObj.properties.outputs.webappname.value
          az webapp config container set `
                        --resource-group ${{ env.resourcegroup }} `
                        --name $webappname `
                        --docker-custom-image-name ${{ env.imagename }}:${{ github.sha }} `
                        --docker-registry-server-password ${{ secrets.REGISTRY_PASSWORD }} `
                        --docker-registry-server-url https://${{ env.containerregistry }} `
                        --docker-registry-server-user ${{ env.registryusername }} `
                        --slot staging
          echo "webAppName=$webAppName" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
        shell: pwsh

      - name: Swap slots for webapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az webapp deployment slot swap -g ${{ env.resourcegroup }} -n ${{ env.webAppName }} --slot staging --target-slot production

  deploy-prod:
    runs-on: ubuntu-latest
    needs: deploy-test
    steps:
      - name: Download armtemplate
        uses: actions/download-artifact@v2
        with:
          name: armtemplate

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy resource group
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az group create -l northeurope -n ${{ env.resourcegroup }}

      - run: |
          $output = az deployment group create --resource-group ${{ env.resourcegroup }} --template-file azuredeploy.json --parameters environment=production --parameters administratorLogin=JallaJalla --parameters administratorLoginPassword=${{ secrets.DBPASSWORD }}
          $armOutputObj = $output | ConvertFrom-Json
          $webAppName = $armOutputObj.properties.outputs.webappname.value
          az webapp config container set `
                        --resource-group ${{ env.resourcegroup }} `
                        --name $webappname `
                        --docker-custom-image-name ${{ env.imagename }}:${{ github.sha }} `
                        --docker-registry-server-password ${{ secrets.REGISTRY_PASSWORD }} `
                        --docker-registry-server-url https://${{ env.containerregistry }} `
                        --docker-registry-server-user ${{ env.registryusername }} `
                        --slot staging
          echo "webAppName=$webAppName" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
        shell: pwsh

      - name: Swap slots for webapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az webapp deployment slot swap -g ${{ env.resourcegroup }} -n ${{ env.webAppName }} --slot staging --target-slot production      
